api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/ApiResources']
    patch_formats:
        json: ['application/merge-patch+json']
    show_webby: false
    title: 'CAR Rental'
    description: 'FACR Laravel project API gateway'
    version: '%api_minor_version%'
    swagger:
        versions: [3]
        api_keys:
            Client Token Value:
                name: client-token
                type: header
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'