api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/ApiResources']
    patch_formats:
        json: ['application/merge-patch+json']
    show_webby: false
    title: 'CAR Rental'
    description: 'FACR Laravel project API gateway'
    version: '1.0.0'
    swagger:
        versions: [3]
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'