version: '3.4'

services:
#
# * Using system in-built PHP/Apache
#
#  php-fpm:
#    container_name: cra_php_fpm
#    build:
#      context: ./docker/php-fpm
#    volumes:
#      - ./app:/var/www/html
#
#  nginx:
#    container_name: cra_nginx
#    build:
#      context: ./docker/nginx
#    volumes:
#      - ./app:/var/www/html
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./docker/nginx/sites/:/etc/nginx/sites-available
#      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
#    ports:
#      - "8088:80"
#      - "8084:443"
#    depends_on:
#      - php-fpm

  database:
    container_name: cra_database
    image: postgres:15-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: 'admin'
        POSTGRES_USER: 'user'
        POSTGRES_DB: 'car_rental'
    volumes:
        - ./docker/database/postgres-data:/var/lib/postgresql/data
        - ./docker/database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
        - '5454:5432'

  redis:
        container_name: cra_redis
        image: redis:alpine
        ports:
            - "6959:6379"

  elasticsearch:
      container_name: cra_elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
      environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - "xpack.security.enabled=false"
          - "discovery.type=single-node"
      ulimits:
          memlock:
              soft: -1
              hard: -1
      ports:
          - "9292:9200"
          - "9393:9300"
      volumes:
          - ./docker/esx/data:/usr/share/elasticsearch/data
          - ./docker/esx/logs:/usr/share/elasticsearch/logs

  mailcatcher:
      container_name: cra_mailcatcher
      restart: on-failure
      image: dockage/mailcatcher:0.8.2
      ports:
          - "1080:1080"
          - "1025:1025"
