parameters:
    api_major_version: '%env(resolve:MAJOR_VERSION)%'
    api_minor_version: '%env(resolve:MINOR_VERSION)%'
    vehicles_type:
        "small-cars" : 1
        "family-cars" : 2
        "suv-cars" : 3
    vehicle_image_url: 'http://firstautocarrental.local/images/booking/{name}'